joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters: {}

diff_cont:
  type: diff_drive_controller/DiffDriveController
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation:  0.80
    wheel_radius:      0.12
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    velocity_rolling_window_size: 10
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 2.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 3.0
