controller_manager:
  ros__parameters:
    use_sim_time: true         # <â€” add this
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation:  0.80
    wheel_radius:      0.12

    base_frame_id:     "base_footprint"
    odom_frame_id:     "odom"
    enable_odom_tf:    true
    publish_rate:      50.0    # must be float
    use_stamped_vel:   true
    cmd_vel_timeout:   0.5

    linear:
      x: {has_velocity_limits: true, max_velocity: 1.2, has_acceleration_limits: true, max_acceleration: 2.0}
    angular:
      z: {has_velocity_limits: true, max_velocity: 2.5, has_acceleration_limits: true, max_acceleration: 4.0}
